###
POST http://localhost:3000/Repartidor/crearRepartidor HTTP/1.1
Content-Type: application/json

{
    "id_repartidor":2,
    "nombre":"Piwa"
}

###
GET http://localhost:3000/Repartidor/conseguirRepartidor/1 HTTP/1.1
Content-Type: application/json

