###
POST http://localhost:3000/Repartidor/crearRepartidor HTTP/1.1
Content-Type: application/json
{
    "nombre":"piwa",
    "direccion":"Piwa"
}

###
GET http://localhost:3000/Repartidor/conseguirRepartidor HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3000/Repartidor/ObtenerRapartidorNuevo HTTP/1.1
Content-Type: application/json
